#include	"activation_functions.hpp"
#include	"embedding_layers.hpp"
#include	"full_connect_layers.hpp"
#include	"memory_layers.hpp"
#include	"loss_function_layers.hpp"
#include	"weightless_layers.hpp"
